---
k3s_cluster:
  children:
    server:
      hosts:
        leader:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
          ip: 10.27.107.1
          k3s_control_node: true
  vars:
    s3_username: 'minio'
    s3_password: 'minio'
    s3_region: 'us-east-1'
    k3s_token: $(openssl rand -hex 32)
    slack_token: ''
    slack_channel_id: ''
    base_dir: '/home/runner/work/scout'
    scout_repo_dir: '{{ base_dir }}/scout'
    #k3s_install_dir: '/home/runner/work/k3s'
    k3s_server:
      docker: true

    # You probably don't want to change these unless you know these items will be
    # stored in different locations on your system
    helm_plugins_dir: '~/.local/share/helm/plugins'
    kubeconfig_yaml: '/etc/rancher/k3s/k3s.yaml'

    # Do not change the values below, they are hard-coded various places
    orchestration_worker_namespace: orchestration-workers
    minio_tenant_namespace: minio-scout
    grafana_namespace: grafana
    loki_namespace: loki
    # End do not change
