---

- name: Hello World Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:
    - name: Log
      debug:
        msg: "Hello world from {{ ansible_net_hostname }}"