name: 'Docker build + cache'
description: 'Builds and caches docker image'
inputs:
  subproject:
    description: 'Subdirectory for microservice'
    required: true
  image-name:
    description: 'Name for docker image'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Derive version'
      id: derive-version
      uses: ./.github/actions/derive-version
      with:
        subproject: ${{ inputs.subproject }}

    - name: 'Build/Cache Image'
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.subproject }}
        tags: ${{ ENV.REGISTRY }}/washu-tag/${{ inputs.image-name }}:${{ steps.derive-version.outputs.version }}
        outputs: type=docker,dest=${{ runner.temp }}/${{ inputs.image-name }}.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.image-name }}
        path: ${{ runner.temp }}/${{ inputs.image-name }}.tar
