name: 'Docker tag local'
description: 'Downloads docker image tags it for testing'
inputs:
  image-name:
    description: 'Name for docker image'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.image-name }}
        path: ${{ runner.temp }}
    - name: Label image
      shell: bash
      run: |
        sudo k3s ctr images import --base-name local/washu-tag/${{ inputs.image-name }} ${{ runner.temp }}/${{ inputs.image-name }}.tar
